version: "3.1"

services:
  api:
    container_name: moviedb-charge-tv-episodes-credits
    image: moviedb-charge-tv-episodes-credits:1.0
    build:
      context: .
      args:
        - GO_ENV=${GO_ENV}
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "3"
        labels: "production_status"
        env: "os"
    restart: on-failure
    # ports:
    #   - "8223:1323"
    environment:
      - GO_ENV=${GO_ENV}

networks:
  default:
    external:
      name: modomeu_network
