version: "3.1"

services:
  api:
    container_name: moviedb-carga-container
    image: moviedb-carga:1.0
    build:
      context: .
      args:
        - NODE_ENV=${NODE_ENV}
    logging:
      driver: "json-file"
      options:
        max-size: 100m
        max-file: "3"
        labels: "production_status"
        env: "os"
    restart: on-failure
    # ports:
    #   - "8223:1323"
    environment:
      - NODE_ENV=${NODE_ENV}

networks:
  default:
    external:
      name: modomeu_network
