# Use uma imagem base do Go
FROM golang:1.25.1-alpine

RUN apk update && apk upgrade --no-cache

ARG GO_ENV
ENV GO_ENV=$GO_ENV

ENV TZ=America/Fortaleza
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos do projeto para o contêiner
COPY . .

# Baixe as dependências
RUN go mod tidy

# Compile o binário
RUN go build -o worker ./workers/catalog-worker.go

# Comando para executar o consumidor
CMD ["./worker"]
